services:
  db:
    image: postgres:latest
    container_name: cinema_db
    restart: always
    environment:
      POSTGRES_PASSWORD: Admino_nymous228
      POSTGRES_DB: cinema_booking_db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - cinema_db_data:/var/lib/postgresql

volumes:
  cinema_db_data: